// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogpageDocumentDataSlicesSlice = never;

/**
 * Content for blogPage documents
 */
interface BlogpageDocumentData {
  /**
   * Titolo field in *blogPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.titolo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titolo: prismic.KeyTextField;

  /**
   * immagine principale field in *blogPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.immagine_principale
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  immagine_principale: prismic.ImageField<never>;

  /**
   * content field in *blogPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *blogPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpageDocumentDataSlicesSlice> /**
   * Meta Title field in *blogPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blogPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blogPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blogPage document from Prismic
 *
 * - **API ID**: `blogpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpageDocumentData>,
    "blogpage",
    Lang
  >;

/**
 * Item in *Clienti → schede*
 */
export interface ClientiDocumentDataSchedeItem {
  /**
   * scheda field in *Clienti → schede*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.schede[].scheda
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  scheda: prismic.LinkField;
}

type ClientiDocumentDataSlicesSlice = never;

/**
 * Content for Clienti documents
 */
interface ClientiDocumentData {
  /**
   * Password field in *Clienti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.password
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  password: prismic.KeyTextField;

  /**
   * nome field in *Clienti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * cognome field in *Clienti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.cognome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cognome: prismic.KeyTextField;

  /**
   * Prossimo appuntamento field in *Clienti*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.calendario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  calendario: prismic.DateField;

  /**
   * schede field in *Clienti*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.schede[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  schede: prismic.GroupField<Simplify<ClientiDocumentDataSchedeItem>>;

  /**
   * Slice Zone field in *Clienti*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientiDocumentDataSlicesSlice> /**
   * Meta Title field in *Clienti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clienti.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Clienti*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clienti.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Clienti*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clienti.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Clienti document from Prismic
 *
 * - **API ID**: `clienti`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClientiDocumentData>,
    "clienti",
    Lang
  >;

export type AllDocumentTypes = BlogpageDocument | ClientiDocument;

/**
 * Primary content in *BlogContent → Default → Primary*
 */
export interface BlogContentSliceDefaultPrimary {
  /**
   * Title field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Content field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for BlogContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogContent*
 */
type BlogContentSliceVariation = BlogContentSliceDefault;

/**
 * BlogContent Shared Slice
 *
 * - **API ID**: `blog_content`
 * - **Description**: BlogContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogContentSlice = prismic.SharedSlice<
  "blog_content",
  BlogContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogpageDocument,
      BlogpageDocumentData,
      BlogpageDocumentDataSlicesSlice,
      ClientiDocument,
      ClientiDocumentData,
      ClientiDocumentDataSchedeItem,
      ClientiDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogContentSlice,
      BlogContentSliceDefaultPrimary,
      BlogContentSliceVariation,
      BlogContentSliceDefault,
    };
  }
}
